### ISSUE TITLE
forward ref is not working when using track as hoc

### ISSUE THREAD

**Issue by shovalk** [nytimes/react-tracking#159] opened 2020-07-30 08:44 UTC
while using track as hoc and setting in options `forwardRef: true` the ref is not being forwarded.
The issue is reproduced and a relevant git repo can be found here - 
https://github.com/shovalk/react-tracking-forwardref-reproduce

**Comment by tizmagik** [comment] 2020-08-11 19:10
Ah thanks for the bug report and reproduction case, @shovalk !

cc @ParadeTo who did the initial implementation. Any ideas?

I'll try and take a closer look at this as soon as I get a chance as well.

Thanks again.

**Comment by cpprookie** [comment] 2020-08-12 02:37
Looks like those commits merged into master but not published in npm package. Latest v7.3.0 was published in 2019. @tizmagik

**Comment by tizmagik** [comment] 2020-08-12 18:42
Ah of course haha sorry! I thought I remembered releasing this, but I guess not. I'll cut a release and hopefully that should address this issue. Thanks @cpprookie !

**Comment by tizmagik** [comment] 2020-08-12 18:52
This was released as [v8.0.0](https://github.com/nytimes/react-tracking/releases/tag/v8.0.0) -- I verified it working with the reproduction repo @shovalk ! Give that a shot and let me know if you have any other issues. Thanks again @cpprookie !

**Closed** 2020-08-13 01:48 UTC
Labels: bug

**Comment by cpprookie** [comment] 2020-08-13 01:58
> Ah of course haha sorry! I thought I remembered releasing this, but I guess not. I'll cut a release and hopefully that should address this issue. Thanks @cpprookie !

Hah, never mind everyone makes mistake. Thanks for the awesome library, it's my pleasure that i could help community. @tizmagik

**Comment by shovalk** [comment] 2020-08-13 07:09
@tizmagik Thank you!
